all:
  hosts:
    node1:
      ansible_host: 10.0.1.12
      ip: 10.0.1.12
      access_ip: 10.0.1.12
      ansible_ssh_private_key_file: /opt/kubespray/vm
      ansible_user: ubuntu
    node2:
      ansible_host: 10.0.1.15
      ip: 10.0.1.15
      access_ip: 10.0.1.15
      ansible_ssh_private_key_file: /opt/kubespray/vm
      ansible_user: ubuntu
    node3:
      ansible_host: 10.0.2.27
      ip: 10.0.2.27
      access_ip: 10.0.2.27
      ansible_ssh_private_key_file: /opt/kubespray/vm
      ansible_user: ubuntu
  children:
    kube_control_plane:
      hosts:
        node1:
    kube_node:
      hosts:
        node2:
        node3:
    etcd:
      hosts:
        node1: 
    k8s_cluster:
      children:
        kube_control_plane:
        kube_node:
    calico_rr:
      hosts: {}
